version: '3'
services:
  web:
    build: .
    command: 'npm run dev -- --auto'
    ports:
      - '9000:9000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
      - 'postgres'

  postgres:
    image: 'postgres:12'
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'db'
