version: '3'
services:
  web:
    build: .
    command: npm run dev -- --auto
    ports:
      - '9000:9000'
    volumes:
      - '.:/app'
      - /app/node_modules
    depends_on:
      - postgres
  postgres:
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - './postgres-data:/var/lib/postgresql'
